/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as predictionMarketSol from "./PredictionMarket.sol";
export type { predictionMarketSol };
import type * as umaMarketResolverSol from "./UMAMarketResolver.sol";
export type { umaMarketResolverSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { MockERC20 } from "./MockERC20";
export type { PredictionMarketFactory } from "./PredictionMarketFactory";
