/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PredictionMarketFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adminCancelMarket"
      | "adminResolveMarket"
      | "allMarkets"
      | "createMarket"
      | "defaultResolver"
      | "getActiveMarkets"
      | "getAllMarkets"
      | "getMarketsByCreator"
      | "getMarketsPaginated"
      | "getTotalMarkets"
      | "isValidMarket"
      | "marketsByCreator"
      | "owner"
      | "setDefaultResolver"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DefaultResolverUpdated"
      | "MarketCreated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adminCancelMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminResolveMarket",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "allMarkets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultResolver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsByCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketsByCreator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDefaultResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminCancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminResolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allMarkets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DefaultResolverUpdatedEvent {
  export type InputTuple = [newResolver: AddressLike];
  export type OutputTuple = [newResolver: string];
  export interface OutputObject {
    newResolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketAddress: AddressLike,
    creator: AddressLike,
    question: string,
    endTime: BigNumberish,
    options: string[]
  ];
  export type OutputTuple = [
    marketAddress: string,
    creator: string,
    question: string,
    endTime: bigint,
    options: string[]
  ];
  export interface OutputObject {
    marketAddress: string;
    creator: string;
    question: string;
    endTime: bigint;
    options: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketFactory;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adminCancelMarket: TypedContractMethod<
    [marketAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  adminResolveMarket: TypedContractMethod<
    [marketAddress: AddressLike, winnerIndices: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  allMarkets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createMarket: TypedContractMethod<
    [_question: string, _endTime: BigNumberish, _options: string[]],
    [string],
    "nonpayable"
  >;

  defaultResolver: TypedContractMethod<[], [string], "view">;

  getActiveMarkets: TypedContractMethod<[], [string[]], "view">;

  getAllMarkets: TypedContractMethod<[], [string[]], "view">;

  getMarketsByCreator: TypedContractMethod<
    [creator: AddressLike],
    [string[]],
    "view"
  >;

  getMarketsPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { markets: string[]; total: bigint }],
    "view"
  >;

  getTotalMarkets: TypedContractMethod<[], [bigint], "view">;

  isValidMarket: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  marketsByCreator: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setDefaultResolver: TypedContractMethod<
    [_resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adminCancelMarket"
  ): TypedContractMethod<[marketAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminResolveMarket"
  ): TypedContractMethod<
    [marketAddress: AddressLike, winnerIndices: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allMarkets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [_question: string, _endTime: BigNumberish, _options: string[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultResolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveMarkets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllMarkets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMarketsByCreator"
  ): TypedContractMethod<[creator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMarketsPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { markets: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalMarkets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isValidMarket"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "marketsByCreator"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDefaultResolver"
  ): TypedContractMethod<[_resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DefaultResolverUpdated"
  ): TypedContractEvent<
    DefaultResolverUpdatedEvent.InputTuple,
    DefaultResolverUpdatedEvent.OutputTuple,
    DefaultResolverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DefaultResolverUpdated(address)": TypedContractEvent<
      DefaultResolverUpdatedEvent.InputTuple,
      DefaultResolverUpdatedEvent.OutputTuple,
      DefaultResolverUpdatedEvent.OutputObject
    >;
    DefaultResolverUpdated: TypedContractEvent<
      DefaultResolverUpdatedEvent.InputTuple,
      DefaultResolverUpdatedEvent.OutputTuple,
      DefaultResolverUpdatedEvent.OutputObject
    >;

    "MarketCreated(address,address,string,uint256,string[])": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
