/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "endTime"
      | "getOptionLabels"
      | "marketStatus"
      | "optionCount"
      | "question"
      | "resolveMarketFromResolver"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "endTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getOptionLabels",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "question", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveMarketFromResolver",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "endTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOptionLabels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "question", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarketFromResolver",
    data: BytesLike
  ): Result;
}

export interface IPredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  endTime: TypedContractMethod<[], [bigint], "view">;

  getOptionLabels: TypedContractMethod<[], [string[]], "view">;

  marketStatus: TypedContractMethod<[], [bigint], "view">;

  optionCount: TypedContractMethod<[], [bigint], "view">;

  question: TypedContractMethod<[], [string], "view">;

  resolveMarketFromResolver: TypedContractMethod<
    [winnerIndices: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "endTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOptionLabels"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "marketStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "optionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "question"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveMarketFromResolver"
  ): TypedContractMethod<[winnerIndices: BigNumberish[]], [void], "nonpayable">;

  filters: {};
}
