/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface UMAMarketResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_LIVENESS"
      | "IDENTIFIER"
      | "MIN_BOND"
      | "bondCurrency"
      | "canSettle"
      | "getOracleState"
      | "getResolutionRequest"
      | "hasPendingRequest"
      | "oracle"
      | "previewAncillaryData"
      | "requestResolution"
      | "resolutionRequests"
      | "settleAndResolve"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketResolved"
      | "ResolutionProposed"
      | "ResolutionRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_LIVENESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IDENTIFIER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_BOND", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bondCurrency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canSettle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolutionRequest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPendingRequest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewAncillaryData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestResolution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolutionRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAndResolve",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_LIVENESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "IDENTIFIER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_BOND", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bondCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canSettle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOracleState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolutionRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPendingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewAncillaryData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolutionRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAndResolve",
    data: BytesLike
  ): Result;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    market: AddressLike,
    winningOption: BigNumberish,
    resolvedPrice: BigNumberish
  ];
  export type OutputTuple = [
    market: string,
    winningOption: bigint,
    resolvedPrice: bigint
  ];
  export interface OutputObject {
    market: string;
    winningOption: bigint;
    resolvedPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionProposedEvent {
  export type InputTuple = [
    market: AddressLike,
    proposer: AddressLike,
    proposedPrice: BigNumberish
  ];
  export type OutputTuple = [
    market: string,
    proposer: string,
    proposedPrice: bigint
  ];
  export interface OutputObject {
    market: string;
    proposer: string;
    proposedPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionRequestedEvent {
  export type InputTuple = [
    market: AddressLike,
    requestTime: BigNumberish,
    ancillaryData: BytesLike
  ];
  export type OutputTuple = [
    market: string,
    requestTime: bigint,
    ancillaryData: string
  ];
  export interface OutputObject {
    market: string;
    requestTime: bigint;
    ancillaryData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UMAMarketResolver extends BaseContract {
  connect(runner?: ContractRunner | null): UMAMarketResolver;
  waitForDeployment(): Promise<this>;

  interface: UMAMarketResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_LIVENESS: TypedContractMethod<[], [bigint], "view">;

  IDENTIFIER: TypedContractMethod<[], [string], "view">;

  MIN_BOND: TypedContractMethod<[], [bigint], "view">;

  bondCurrency: TypedContractMethod<[], [string], "view">;

  canSettle: TypedContractMethod<[market: AddressLike], [boolean], "view">;

  getOracleState: TypedContractMethod<[market: AddressLike], [bigint], "view">;

  getResolutionRequest: TypedContractMethod<
    [market: AddressLike],
    [
      [bigint, string, boolean, bigint] & {
        requestTime: bigint;
        ancillaryData: string;
        resolved: boolean;
        winningOption: bigint;
      }
    ],
    "view"
  >;

  hasPendingRequest: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  previewAncillaryData: TypedContractMethod<
    [market: AddressLike],
    [string],
    "view"
  >;

  requestResolution: TypedContractMethod<
    [market: AddressLike],
    [void],
    "nonpayable"
  >;

  resolutionRequests: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, boolean, bigint] & {
        market: string;
        requestTime: bigint;
        ancillaryData: string;
        resolved: boolean;
        winningOption: bigint;
      }
    ],
    "view"
  >;

  settleAndResolve: TypedContractMethod<
    [market: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_LIVENESS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IDENTIFIER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bondCurrency"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canSettle"
  ): TypedContractMethod<[market: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getOracleState"
  ): TypedContractMethod<[market: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResolutionRequest"
  ): TypedContractMethod<
    [market: AddressLike],
    [
      [bigint, string, boolean, bigint] & {
        requestTime: bigint;
        ancillaryData: string;
        resolved: boolean;
        winningOption: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPendingRequest"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewAncillaryData"
  ): TypedContractMethod<[market: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "requestResolution"
  ): TypedContractMethod<[market: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolutionRequests"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, boolean, bigint] & {
        market: string;
        requestTime: bigint;
        ancillaryData: string;
        resolved: boolean;
        winningOption: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "settleAndResolve"
  ): TypedContractMethod<[market: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionProposed"
  ): TypedContractEvent<
    ResolutionProposedEvent.InputTuple,
    ResolutionProposedEvent.OutputTuple,
    ResolutionProposedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionRequested"
  ): TypedContractEvent<
    ResolutionRequestedEvent.InputTuple,
    ResolutionRequestedEvent.OutputTuple,
    ResolutionRequestedEvent.OutputObject
  >;

  filters: {
    "MarketResolved(address,uint8,int256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "ResolutionProposed(address,address,int256)": TypedContractEvent<
      ResolutionProposedEvent.InputTuple,
      ResolutionProposedEvent.OutputTuple,
      ResolutionProposedEvent.OutputObject
    >;
    ResolutionProposed: TypedContractEvent<
      ResolutionProposedEvent.InputTuple,
      ResolutionProposedEvent.OutputTuple,
      ResolutionProposedEvent.OutputObject
    >;

    "ResolutionRequested(address,uint256,bytes)": TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;
    ResolutionRequested: TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;
  };
}
