/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOptimisticOracleV2 {
  export type RequestStruct = {
    proposer: AddressLike;
    disputer: AddressLike;
    currency: AddressLike;
    settled: boolean;
    refundOnDispute: boolean;
    proposedPrice: BigNumberish;
    resolvedPrice: BigNumberish;
    expirationTime: BigNumberish;
    reward: BigNumberish;
    finalFee: BigNumberish;
    bond: BigNumberish;
    customLiveness: BigNumberish;
  };

  export type RequestStructOutput = [
    proposer: string,
    disputer: string,
    currency: string,
    settled: boolean,
    refundOnDispute: boolean,
    proposedPrice: bigint,
    resolvedPrice: bigint,
    expirationTime: bigint,
    reward: bigint,
    finalFee: bigint,
    bond: bigint,
    customLiveness: bigint
  ] & {
    proposer: string;
    disputer: string;
    currency: string;
    settled: boolean;
    refundOnDispute: boolean;
    proposedPrice: bigint;
    resolvedPrice: bigint;
    expirationTime: bigint;
    reward: bigint;
    finalFee: bigint;
    bond: bigint;
    customLiveness: bigint;
  };
}

export interface IOptimisticOracleV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRequest"
      | "getState"
      | "hasPrice"
      | "proposePrice"
      | "requestPrice"
      | "setCustomLiveness"
      | "settle"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRequest",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getState",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPrice",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposePrice",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestPrice",
    values: [BytesLike, BigNumberish, BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCustomLiveness",
    values: [BytesLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCustomLiveness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
}

export interface IOptimisticOracleV2 extends BaseContract {
  connect(runner?: ContractRunner | null): IOptimisticOracleV2;
  waitForDeployment(): Promise<this>;

  interface: IOptimisticOracleV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRequest: TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [IOptimisticOracleV2.RequestStructOutput],
    "view"
  >;

  getState: TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [bigint],
    "view"
  >;

  hasPrice: TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [boolean],
    "view"
  >;

  proposePrice: TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      proposedPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  requestPrice: TypedContractMethod<
    [
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: AddressLike,
      reward: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  setCustomLiveness: TypedContractMethod<
    [
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      customLiveness: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settle: TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [IOptimisticOracleV2.RequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getState"
  ): TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPrice"
  ): TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposePrice"
  ): TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      proposedPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestPrice"
  ): TypedContractMethod<
    [
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: AddressLike,
      reward: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCustomLiveness"
  ): TypedContractMethod<
    [
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      customLiveness: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<
    [
      requester: AddressLike,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
