/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BatchPrediction__factory } from "./BatchPrediction__factory";
export { IPredictionMarket__factory } from "./IPredictionMarket__factory";
