/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyShares"
      | "calculatePotentialPayout"
      | "calculateSellPayout"
      | "cancelMarket"
      | "claimRefund"
      | "claimWinnings"
      | "collateralToken"
      | "createdAt"
      | "creator"
      | "endTime"
      | "getContractBalance"
      | "getMarketInfo"
      | "getOdds"
      | "getOptionLabel"
      | "getOptionLabels"
      | "getOptionPrice"
      | "getTimeRemaining"
      | "getTotalPool"
      | "getTotalShares"
      | "getUserPosition"
      | "getUserShares"
      | "getWinningOptions"
      | "hasClaimed"
      | "hasWinners"
      | "isOpenForBetting"
      | "marketStatus"
      | "optionCount"
      | "optionLabels"
      | "question"
      | "resolveMarket"
      | "sellShares"
      | "shares"
      | "totalShares"
      | "winningOptions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "MarketCancelled"
      | "MarketCreated"
      | "MarketResolved"
      | "Refunded"
      | "SharesBought"
      | "SharesSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePotentialPayout",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSellPayout",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(functionFragment: "endTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOdds", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getOptionLabel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionLabels",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeRemaining",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserShares",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinningOptions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWinners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOpenForBetting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionLabels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "question", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sellShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shares",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winningOptions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePotentialPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSellPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOdds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOptionLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionLabels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinningOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasWinners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isOpenForBetting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionLabels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "question", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winningOptions",
    data: BytesLike
  ): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [user: AddressLike, payout: BigNumberish];
  export type OutputTuple = [user: string, payout: bigint];
  export interface OutputObject {
    user: string;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [cancelledBy: AddressLike];
  export type OutputTuple = [cancelledBy: string];
  export interface OutputObject {
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    question: string,
    endTime: BigNumberish,
    options: string[]
  ];
  export type OutputTuple = [
    creator: string,
    question: string,
    endTime: bigint,
    options: string[]
  ];
  export interface OutputObject {
    creator: string;
    question: string;
    endTime: bigint;
    options: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    winnerIndices: BigNumberish[],
    totalPool: BigNumberish
  ];
  export type OutputTuple = [winnerIndices: bigint[], totalPool: bigint];
  export interface OutputObject {
    winnerIndices: bigint[];
    totalPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesBoughtEvent {
  export type InputTuple = [
    buyer: AddressLike,
    optionIndex: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    optionIndex: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    buyer: string;
    optionIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    optionIndex: BigNumberish,
    sharesAmount: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    optionIndex: bigint,
    sharesAmount: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    seller: string;
    optionIndex: bigint;
    sharesAmount: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyShares: TypedContractMethod<
    [optionIndex: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  calculatePotentialPayout: TypedContractMethod<
    [user: AddressLike, winnerIndices: BigNumberish[]],
    [bigint],
    "view"
  >;

  calculateSellPayout: TypedContractMethod<
    [optionIndex: BigNumberish, sharesAmount: BigNumberish],
    [bigint],
    "view"
  >;

  cancelMarket: TypedContractMethod<[], [void], "nonpayable">;

  claimRefund: TypedContractMethod<[], [void], "nonpayable">;

  claimWinnings: TypedContractMethod<[], [void], "nonpayable">;

  collateralToken: TypedContractMethod<[], [string], "view">;

  createdAt: TypedContractMethod<[], [bigint], "view">;

  creator: TypedContractMethod<[], [string], "view">;

  endTime: TypedContractMethod<[], [bigint], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getMarketInfo: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string[],
        bigint[],
        boolean[],
        bigint
      ] & {
        _creator: string;
        _question: string;
        _endTime: bigint;
        _createdAt: bigint;
        _status: bigint;
        _optionCount: bigint;
        _optionLabels: string[];
        _totalShares: bigint[];
        _winningOptions: boolean[];
        _totalPool: bigint;
      }
    ],
    "view"
  >;

  getOdds: TypedContractMethod<[], [bigint[]], "view">;

  getOptionLabel: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getOptionLabels: TypedContractMethod<[], [string[]], "view">;

  getOptionPrice: TypedContractMethod<
    [optionIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getTimeRemaining: TypedContractMethod<[], [bigint], "view">;

  getTotalPool: TypedContractMethod<[], [bigint], "view">;

  getTotalShares: TypedContractMethod<[], [bigint[]], "view">;

  getUserPosition: TypedContractMethod<
    [user: AddressLike],
    [[bigint[], boolean] & { _shares: bigint[]; _hasClaimed: boolean }],
    "view"
  >;

  getUserShares: TypedContractMethod<
    [user: AddressLike, optionIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getWinningOptions: TypedContractMethod<[], [boolean[]], "view">;

  hasClaimed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasWinners: TypedContractMethod<[], [boolean], "view">;

  isOpenForBetting: TypedContractMethod<[], [boolean], "view">;

  marketStatus: TypedContractMethod<[], [bigint], "view">;

  optionCount: TypedContractMethod<[], [bigint], "view">;

  optionLabels: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  question: TypedContractMethod<[], [string], "view">;

  resolveMarket: TypedContractMethod<
    [winnerIndices: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  sellShares: TypedContractMethod<
    [optionIndex: BigNumberish, sharesAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  shares: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  totalShares: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  winningOptions: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyShares"
  ): TypedContractMethod<
    [optionIndex: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculatePotentialPayout"
  ): TypedContractMethod<
    [user: AddressLike, winnerIndices: BigNumberish[]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateSellPayout"
  ): TypedContractMethod<
    [optionIndex: BigNumberish, sharesAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createdAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "endTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string[],
        bigint[],
        boolean[],
        bigint
      ] & {
        _creator: string;
        _question: string;
        _endTime: bigint;
        _createdAt: bigint;
        _status: bigint;
        _optionCount: bigint;
        _optionLabels: string[];
        _totalShares: bigint[];
        _winningOptions: boolean[];
        _totalPool: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOdds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOptionLabel"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getOptionLabels"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getOptionPrice"
  ): TypedContractMethod<[optionIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimeRemaining"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalShares"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserPosition"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint[], boolean] & { _shares: bigint[]; _hasClaimed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserShares"
  ): TypedContractMethod<
    [user: AddressLike, optionIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinningOptions"
  ): TypedContractMethod<[], [boolean[]], "view">;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasWinners"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOpenForBetting"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "marketStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "optionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "optionLabels"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "question"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<[winnerIndices: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellShares"
  ): TypedContractMethod<
    [optionIndex: BigNumberish, sharesAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shares"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "winningOptions"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "SharesBought"
  ): TypedContractEvent<
    SharesBoughtEvent.InputTuple,
    SharesBoughtEvent.OutputTuple,
    SharesBoughtEvent.OutputObject
  >;
  getEvent(
    key: "SharesSold"
  ): TypedContractEvent<
    SharesSoldEvent.InputTuple,
    SharesSoldEvent.OutputTuple,
    SharesSoldEvent.OutputObject
  >;

  filters: {
    "Claimed(address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "MarketCancelled(address)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketCreated(address,string,uint256,string[])": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint8[],uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "Refunded(address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "SharesBought(address,uint8,uint256)": TypedContractEvent<
      SharesBoughtEvent.InputTuple,
      SharesBoughtEvent.OutputTuple,
      SharesBoughtEvent.OutputObject
    >;
    SharesBought: TypedContractEvent<
      SharesBoughtEvent.InputTuple,
      SharesBoughtEvent.OutputTuple,
      SharesBoughtEvent.OutputObject
    >;

    "SharesSold(address,uint8,uint256,uint256)": TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;
    SharesSold: TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;
  };
}
