/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BatchPrediction {
  export type PredictionStruct = {
    market: AddressLike;
    optionIndex: BigNumberish;
    amount: BigNumberish;
  };

  export type PredictionStructOutput = [
    market: string,
    optionIndex: bigint,
    amount: bigint
  ] & { market: string; optionIndex: bigint; amount: bigint };
}

export interface BatchPredictionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchPredict"
      | "batchPredictSimple"
      | "emergencyWithdraw"
      | "owner"
      | "transferOwnership"
      | "validatePredictions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchPredictionExecuted"
      | "PredictionFailed"
      | "PredictionPlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchPredict",
    values: [BatchPrediction.PredictionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchPredictSimple",
    values: [AddressLike[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatePredictions",
    values: [AddressLike[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchPredict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchPredictSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatePredictions",
    data: BytesLike
  ): Result;
}

export namespace BatchPredictionExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    totalAmount: BigNumberish,
    marketsCount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    totalAmount: bigint,
    marketsCount: bigint
  ];
  export interface OutputObject {
    user: string;
    totalAmount: bigint;
    marketsCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionFailedEvent {
  export type InputTuple = [
    user: AddressLike,
    market: AddressLike,
    optionIndex: BigNumberish,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    user: string,
    market: string,
    optionIndex: bigint,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    user: string;
    market: string;
    optionIndex: bigint;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionPlacedEvent {
  export type InputTuple = [
    user: AddressLike,
    market: AddressLike,
    optionIndex: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    market: string,
    optionIndex: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    market: string;
    optionIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BatchPrediction extends BaseContract {
  connect(runner?: ContractRunner | null): BatchPrediction;
  waitForDeployment(): Promise<this>;

  interface: BatchPredictionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchPredict: TypedContractMethod<
    [predictions: BatchPrediction.PredictionStruct[]],
    [void],
    "payable"
  >;

  batchPredictSimple: TypedContractMethod<
    [
      markets: AddressLike[],
      optionIndices: BigNumberish[],
      amounts: BigNumberish[]
    ],
    [void],
    "payable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validatePredictions: TypedContractMethod<
    [markets: AddressLike[], amounts: BigNumberish[]],
    [[boolean[], bigint] & { valid: boolean[]; totalAmount: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchPredict"
  ): TypedContractMethod<
    [predictions: BatchPrediction.PredictionStruct[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "batchPredictSimple"
  ): TypedContractMethod<
    [
      markets: AddressLike[],
      optionIndices: BigNumberish[],
      amounts: BigNumberish[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validatePredictions"
  ): TypedContractMethod<
    [markets: AddressLike[], amounts: BigNumberish[]],
    [[boolean[], bigint] & { valid: boolean[]; totalAmount: bigint }],
    "view"
  >;

  getEvent(
    key: "BatchPredictionExecuted"
  ): TypedContractEvent<
    BatchPredictionExecutedEvent.InputTuple,
    BatchPredictionExecutedEvent.OutputTuple,
    BatchPredictionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionFailed"
  ): TypedContractEvent<
    PredictionFailedEvent.InputTuple,
    PredictionFailedEvent.OutputTuple,
    PredictionFailedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionPlaced"
  ): TypedContractEvent<
    PredictionPlacedEvent.InputTuple,
    PredictionPlacedEvent.OutputTuple,
    PredictionPlacedEvent.OutputObject
  >;

  filters: {
    "BatchPredictionExecuted(address,uint256,uint256)": TypedContractEvent<
      BatchPredictionExecutedEvent.InputTuple,
      BatchPredictionExecutedEvent.OutputTuple,
      BatchPredictionExecutedEvent.OutputObject
    >;
    BatchPredictionExecuted: TypedContractEvent<
      BatchPredictionExecutedEvent.InputTuple,
      BatchPredictionExecutedEvent.OutputTuple,
      BatchPredictionExecutedEvent.OutputObject
    >;

    "PredictionFailed(address,address,uint8,uint256,string)": TypedContractEvent<
      PredictionFailedEvent.InputTuple,
      PredictionFailedEvent.OutputTuple,
      PredictionFailedEvent.OutputObject
    >;
    PredictionFailed: TypedContractEvent<
      PredictionFailedEvent.InputTuple,
      PredictionFailedEvent.OutputTuple,
      PredictionFailedEvent.OutputObject
    >;

    "PredictionPlaced(address,address,uint8,uint256)": TypedContractEvent<
      PredictionPlacedEvent.InputTuple,
      PredictionPlacedEvent.OutputTuple,
      PredictionPlacedEvent.OutputObject
    >;
    PredictionPlaced: TypedContractEvent<
      PredictionPlacedEvent.InputTuple,
      PredictionPlacedEvent.OutputTuple,
      PredictionPlacedEvent.OutputObject
    >;
  };
}
