/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BatchPrediction } from "./BatchPrediction";
export type { IPredictionMarket } from "./IPredictionMarket";
