/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPredictionMarket__factory } from "./IPredictionMarket__factory";
export { UMAMarketResolver__factory } from "./UMAMarketResolver__factory";
